backend:
  name: github
  repo: mpalash/octopus.git # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "source/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "public/images" # The src attribute for uploaded media will begin with /images/uploads
